name: Check matrix results
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      run_result: "${{ steps.gen-results.outcome == 'success' && 'PASSED' || 'FAILED' }}"
    strategy:
      fail-fast: false
      matrix:
        shard: [1/3, 2/3, 3/3]

    steps:
      - name: Generate results
        id: gen-results
        run: |
          echo "${{ matrix.shard }}"
          if [ "${{ matrix.shard }}" = "2/3" ]; then
            exit 1
          fi

      - name: Print results
        id: print-results
        run: |
          echo "${{ steps.gen-results.outcome }}"
    
  previous_result:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print result from other job
        id: print-job-results
        run: |
          echo "${{ needs.test.outputs.run_result }}"